### ISSUE TITLE
Not Reporting for Android

### ISSUE THREAD

**Issue by blackburnian** [SudoPlz/react-native-bugsnag#22]
Currently I tested using bugsnag.notify(), and it is reporting correctly for iOS.  But the error is not reported when testing in Android (Samsung Galaxy S6 running Android version 5.1.1).  I followed all steps here to configure for Android:
https://github.com/SudoPlz/react-native-bugsnag/wiki/Step-4:-Configuring-the-Android-project-(if-needed)

Any ideas why it's not working for android?

**Comment by blackburnian** [comment]
The project type in Bugsnag is a javascript project.

**Comment by dwilt** [comment]
@SudoPlz this is holding our project up at the moment. I've mentioned over in #23 that we weren't even able to test the example project. Please let us know if you'll get a chance to get to this as we're holding our Android release up to the App Store because we don't want to release without having visibility into any crashes they our users are running into.

**Comment by dwilt** [comment]
This actually seems to be working. We didn't think it was because the emails weren't coming in but they were being logged in Bugnsag. @blackburnian go ahead and close

**Comment by SudoPlz** [comment]
Sorry for taking that long to respond, I'm SUUUPER busy those days..! I'm glad everything worked out for you!
