### ISSUE TITLE
How to add API key?

### ISSUE THREAD

**Issue by GeoffreyPlitt** [SudoPlz/react-native-bugsnag#27]
Hello,

I don't see any reference to the API key in the JS code or examples. If I dive deep into the examples, I see:

```
iOS: Go to the Info.plist within the iOS native project and add your ApiKey,{'\n\n'}
Android: Then go to the manifest.xml within the Android native project and add your ApiKey.
```

This is still confusing, it tells us the value (api key) but not the key.

Would be great to add all this to README.

**Comment by SudoPlz** [comment]
For iOS [here is](https://github.com/SudoPlz/react-native-bugsnag/blob/master/Example/ios/Example/Info.plist#L6) where your key goes.

For Android your key goes [here](https://github.com/SudoPlz/react-native-bugsnag/blob/master/Example/android/app/src/main/AndroidManifest.xml#L28)

I will fix those docs now since they cause confusion!

**Comment by SudoPlz** [comment]
The docs actually tell you about the API key, on the [iOS docs ](https://github.com/SudoPlz/react-native-bugsnag/wiki/Step-3:-Configuring-the-iOS-project-%28if-needed%29) and on the [Android docs](https://github.com/SudoPlz/react-native-bugsnag/wiki/Step-4:-Configuring-the-Android-project-%28if-needed%29).

**Comment by GeoffreyPlitt** [comment]
Perfect, thanks!
