### ISSUE TITLE
unknown exception

### ISSUE THREAD

**Issue by enapupe** [SudoPlz/react-native-bugsnag#3]
I don't really have much information on this issue.. Except that native crash reports are being submitted successfully, but not exceptions manually submitted via js:

`Bugsnag.notify("TestExceptionName", "TestExceptionReason", "error")`

![screen shot 2016-08-17 at 10 39 01 am 1](https://cloud.githubusercontent.com/assets/291082/17738257/ec31e1c0-6466-11e6-937d-97f15846bbb1.png)

**Comment by SudoPlz** [comment]
Thats totally my bad. The documentation was wrong I just fixed it. 

You should call Bugsnag like so:

`Bugsnag().notify("TestExceptionName", "TestExceptionReason", "error")` with parenthesis next to `Bugsnag`. 

The reason you're getting an error thrown is because you don't have a parenthesis next to the word `Bugsnag`.

If that solved your problem please let me know and I'll reopen the issue.

**Comment by enapupe** [comment]
Actually. The Bugsnag object I was referencing was an already intialiazed bugsnag instance.. Like:

```
import Bugsnag from 'react-native-bugsnag'
bs = new Bugsnag()
bs.notify("TestExceptionName", "TestExceptionReason", "error")
```

**Comment by enapupe** [comment]
Oh well.. now with the update in the docs I get it..
I have to say that it feels very wrong to call `Bugnag()` without the `new` operator..

**Comment by SudoPlz** [comment]
Exactly, so the problem was calling Bugsnag with `new` after all. But its a singleton. Perhaps if we created a method called `getInstance()` that would make it less confusing to future users.

For now I just updated the docs to make that more clear https://github.com/SudoPlz/react-native-bugsnag/commit/91b94d9c2cbed4b0086fcbc67e0acae247548a0b
