### ISSUE TITLE
installation breaks xcode build

### ISSUE THREAD

**Issue by davidgruebl** [SudoPlz/react-native-bugsnag#7]
after installing as described the following error occurs when building the xcode project:
<img width="1656" alt="screenshot 2016-08-24 11 46 51" src="https://cloud.githubusercontent.com/assets/5738104/17927653/f320f580-69f6-11e6-997d-139472f50967.png">

react-native version: 0.31.0

**Comment by SudoPlz** [comment]
If I were you I'd play with `Header Search Paths` and `Framework Search Paths` on Project Settings. 

**Important question**: Did you install using Cocoapods?

**Comment by davidgruebl** [comment]
Yes, I am using cocoapods for all native dependencies.
I did play around with the paths, also with the Library Paths (I guess that's where something is going wrong) - couldn't make it work.
For now I've decided to give [sentry](https://docs.sentry.io/hosted/clients/javascript/integrations/react-native/) a go, but I might check back here later.
So if you can't reproduce I guess you can close this issue for now.
Thanks for you support!

**Comment by SudoPlz** [comment]
Ok sure, but if you want to get back @ this give the following a try:
1. Clear everything from your target `Framework Search paths` so that it becomes like this:
   ![screen shot 2016-08-24 at 18 44 44](https://cloud.githubusercontent.com/assets/3070948/17937492/f66a55fe-6a2a-11e6-8969-21da4ba2e738.png)
2. Then make sure your `Header Search Paths` look something like this:
   ![screen shot 2016-08-24 at 18 44 26](https://cloud.githubusercontent.com/assets/3070948/17937514/0a5eadb2-6a2b-11e6-8ac1-048db79f7844.png)

I'll close for now but let me know if that fixed your problem.
